[package]
name = "server"
version = "0.1.0"
edition = "2024"
default-run = "server"

[lints]
workspace = true

[dependencies]
axum = "0.8.9"
config = "0.15.25"
git2 = "0.21.0"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.7.1", features = ["cors"] }
utoipa = { version = "5.5.0", features = ["axum_extras"] }
utoipa-axum = "0.2.0"

[dev-dependencies]
tempfile = "3"
